language: r
r:
  - devel
  - release
cache: packages
dist: trusty
sudo: required

warnings_are_errors: true

apt_packages:
  - qpdf

r_packages:
  - devtools

r_github_packages:
  - cran/callr
  - hadley/pkgdown

script:
  - R CMD build . ${R_BUILD_ARGS}
  - R CMD check ${R_CHECK_ARGS}$ `ls -1t *.tar.gz | head -n 1`
  - R CMD INSTALL `ls -1t *.tar.gz | head -n 1`

notifications:
  email: false

after_success:
  - Rscript -e 'pkgdown::build_site()'
  - mv docs ..
  - rm -r *
  - mv ../docs/* .

after_failure:
  - cat imbalance.Rcheck/00check.log
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_TOKEN
  on:
    branch: master
  target_branch: gh-pages
  
env:
   global:
     - R_BUILD_ARGS="--compact-vignettes=gs+qpdf"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

cran: http://cran.rstudio.com
